




$(".lcl_followers_count").text(chrome.i18n.getMessage("lcl_followers_count"))
$(".lcl_following_count").text(chrome.i18n.getMessage("lcl_following_count"))
$(".lcl_medias_count").text(chrome.i18n.getMessage("lcl_medias_count"))
$(".lcl_filter_public").text(chrome.i18n.getMessage("lcl_filter_public"))
$(".lcl_filter_private").text(chrome.i18n.getMessage("lcl_filter_private"))
$(".lcl_filter_private_public").text(chrome.i18n.getMessage("lcl_filter_private_public"))
$(".lcl_filter_external_link").text(chrome.i18n.getMessage("lcl_filter_external_link"))
$(".lcl_filter_desciription_black").text(chrome.i18n.getMessage("lcl_filter_desciription_black"))
$(".lcl_larger_than").text(chrome.i18n.getMessage("lcl_larger_than"))
$(".lcl_smaller_than").text(chrome.i18n.getMessage("lcl_smaller_than"))
$('.lcl_loading').text(chrome.i18n.getMessage('lcl_loading'))
document.getElementById('lcl_keep_login').innerHTML = chrome.i18n.getMessage('lcl_keep_login');
$('.lcl_email_promo').text(chrome.i18n.getMessage('lcl_email_promo'))
$('.lcl_invite_promo').text(chrome.i18n.getMessage('lcl_invite_promo'))
$('.lcl_waiting').text(chrome.i18n.getMessage('lcl_waiting'))
document.getElementById('lcl_request_reopen').innerHTML = chrome.i18n.getMessage('lcl_request_reopen');
$(".lcl_pool_jobs").text(chrome.i18n.getMessage("lcl_pool_jobs"))
$(".lcl_settings").text(chrome.i18n.getMessage("lcl_settings"))
$(".lcl_sleep_times").text(chrome.i18n.getMessage("lcl_sleep_times"))
$(".lcl_white_list").text(chrome.i18n.getMessage("lcl_white_list"))


$(".lcl_pool").text(chrome.i18n.getMessage("lcl_pool"))

$(".lcl_scanned_users").text(chrome.i18n.getMessage("lcl_scanned_users"))

$(".lcl_remove_unfollow_job").text(chrome.i18n.getMessage("lcl_remove_unfollow_job"))
$('.lcl_cancel').text(chrome.i18n.getMessage('lcl_cancel'))


$(".lcl_user_name").text(chrome.i18n.getMessage("lcl_user_name"))
$(".lcl_follow_time").text(chrome.i18n.getMessage("lcl_follow_time"))
$(".lcl_unfollow_time").text(chrome.i18n.getMessage("lcl_unfollow_time"))
$(".lcl_media").text(chrome.i18n.getMessage("lcl_media"))
$(".lcl_time").text(chrome.i18n.getMessage("lcl_time"))

$(".lcl_error_log").text(chrome.i18n.getMessage("lcl_error_log"))
$(".lcl_action").text(chrome.i18n.getMessage("lcl_action"))
$(".lcl_item").text(chrome.i18n.getMessage("lcl_item"))
$(".lcl_error_type").text(chrome.i18n.getMessage("lcl_error_type"))
$(".lcl_next_action_time").text(chrome.i18n.getMessage("lcl_next_action_time"))
$(".lcl_user_names_desc").text(chrome.i18n.getMessage("lcl_user_names_desc"))




$(".lcl_declare_sleep_times_follow").text(chrome.i18n.getMessage("lcl_declare_sleep_times_follow"))
$(".lcl_declare_sleep_times_unfollow").text(chrome.i18n.getMessage("lcl_declare_sleep_times_unfollow"))
$(".lcl_declare_sleep_times_like").text(chrome.i18n.getMessage("lcl_declare_sleep_times_like"))
$(".lcl_start_time").text(chrome.i18n.getMessage("lcl_start_time"))
$(".lcl_end_time").text(chrome.i18n.getMessage("lcl_end_time"))
$(".lcl_add").text(chrome.i18n.getMessage("lcl_add"))
$(".lcl_delete").text(chrome.i18n.getMessage("lcl_delete"))
$(".lcl_tags_to_collect_media").text(chrome.i18n.getMessage("lcl_tags_to_collect_media"))

$(".lcl_collect_medias_from_home_timeline_to_like").text(chrome.i18n.getMessage("lcl_collect_medias_from_home_timeline_to_like"))
$(".lcl_collect_medias_from_tags_to_like").text(chrome.i18n.getMessage("lcl_collect_medias_from_tags_to_like"))
$(".lcl_like_interval_time").text(chrome.i18n.getMessage("lcl_like_interval_time"))
$(".lcl_error_like_interval_time").text(chrome.i18n.getMessage("lcl_error_like_interval_time"))
$(".lcl_max_like_limit").text(chrome.i18n.getMessage("lcl_max_like_limit"))
$(".lcl_followers").text(chrome.i18n.getMessage("lcl_followers"))
$(".lcl_comments_likes").text(chrome.i18n.getMessage("lcl_comments_likes"))
$(".lcl_searches").text(chrome.i18n.getMessage("lcl_searches"))
$(".lcl_locations").text(chrome.i18n.getMessage("lcl_locations"))
$(".lcl_from_followers").text(chrome.i18n.getMessage("lcl_from_followers"))
$(".lcl_from_comments_likes").text(chrome.i18n.getMessage("lcl_from_comments_likes"))
$(".lcl_from_searches").text(chrome.i18n.getMessage("lcl_from_searches"))
$(".lcl_from_locations").text(chrome.i18n.getMessage("lcl_from_locations"))


$('.lcl_log').text(chrome.i18n.getMessage('lcl_log'))
$('.lcl_delete_pool').text(chrome.i18n.getMessage('lcl_delete_pool'))
$(".lcl_jobs").text(chrome.i18n.getMessage("lcl_jobs"))
$(".lcl_interval_time").text(chrome.i18n.getMessage("lcl_interval_time"))
$(".lcl_after_rate_limit_error").text(chrome.i18n.getMessage("lcl_after_rate_limit_error"))
$(".lcl_follow").text(chrome.i18n.getMessage("lcl_follow"))
$(".lcl_unfollow").text(chrome.i18n.getMessage("lcl_unfollow"))
$(".lcl_pool_collect_followers").text(chrome.i18n.getMessage("lcl_pool_collect_followers"))
$(".lcl_pool_collect_commenters").text(chrome.i18n.getMessage("lcl_pool_collect_commenters"))
$(".lcl_pool_collect_searches").text(chrome.i18n.getMessage("lcl_pool_collect_searches"))
$(".lcl_pool_collect_locations").text(chrome.i18n.getMessage("lcl_pool_collect_locations"))

$(".lcl_follow_limit").text(chrome.i18n.getMessage("lcl_follow_limit"))
$(".lcl_unfollow_limit").text(chrome.i18n.getMessage("lcl_unfollow_limit"))
$(".lcl_follows").text(chrome.i18n.getMessage("lcl_follows"))
$(".lcl_unfollows").text(chrome.i18n.getMessage("lcl_unfollows"))
$(".lcl_likes").text(chrome.i18n.getMessage("lcl_likes"))

$(".lcl_until_1").text(chrome.i18n.getMessage("lcl_until_1"))
$(".lcl_until_2").text(chrome.i18n.getMessage("lcl_until_2"))
$(".lcl_until_3").text(chrome.i18n.getMessage("lcl_until_3"))
$(".lcl_dont_unfollow_followers").text(chrome.i18n.getMessage("lcl_dont_unfollow_followers"))




$(".lcl_collect_current_follows").text(chrome.i18n.getMessage("lcl_collect_current_follows"))
$(".lcl_stop_collect_current_follows").text(chrome.i18n.getMessage("lcl_stop_collect_current_follows"))
$(".lcl_auto_unfollow").text(chrome.i18n.getMessage("lcl_auto_unfollow"))
$(".lcl_auto_unfollow_enable").text(chrome.i18n.getMessage("lcl_auto_unfollow_enable"))
$(".lcl_auto_unfollow_day").text(chrome.i18n.getMessage("lcl_auto_unfollow_day"))
$(".lcl_day_1").text(chrome.i18n.getMessage("lcl_day_1"))
$(".lcl_day_2").text(chrome.i18n.getMessage("lcl_day_2"))
$(".lcl_day_3").text(chrome.i18n.getMessage("lcl_day_3"))
$(".lcl_collect_comments").text(chrome.i18n.getMessage("lcl_collect_comments"))
$(".lcl_collect_likes").text(chrome.i18n.getMessage("lcl_collect_likes"))
$(".lcl_collect_title").text(chrome.i18n.getMessage("lcl_collect_title"))
$(".lcl_delete_white_list_likes_comments").text(chrome.i18n.getMessage("lcl_delete_white_list_likes_comments"))

$('.lcl_data_management').text(chrome.i18n.getMessage('lcl_data_management'))
$('.hide_show').text(chrome.i18n.getMessage('hide_show'))
$('.lcl_backup_desc').text(chrome.i18n.getMessage('lcl_backup_desc'))
$('.lcl_backup_title').text(chrome.i18n.getMessage('lcl_backup_title'))
$('.lcl_backup_export_desc').text(chrome.i18n.getMessage('lcl_backup_export_desc'))
$('.lcl_backup_recover_title').text(chrome.i18n.getMessage('lcl_backup_recover_title'))
$('.lcl_backup_recover_desc').text(chrome.i18n.getMessage('lcl_backup_recover_desc'))

// FAQs
$('.lcl_frequently_asked_questions').text(chrome.i18n.getMessage('lcl_frequently_asked_questions'))
$(".lcl_about_pools").text(chrome.i18n.getMessage("lcl_about_pools"))
$(".lcl_faq_pool_q1").text(chrome.i18n.getMessage("lcl_faq_pool_q1"))
$(".lcl_faq_pool_q2").text(chrome.i18n.getMessage("lcl_faq_pool_q2"))
$(".lcl_faq_pool_q3").text(chrome.i18n.getMessage("lcl_faq_pool_q3"))
$('.lcl_about_speed').text(chrome.i18n.getMessage('lcl_about_speed'))
$('.lcl_faq_speed_q1').text(chrome.i18n.getMessage('lcl_faq_speed_q1'))
$('.lcl_faq_speed_q2').text(chrome.i18n.getMessage('lcl_faq_speed_q2'))
$('.lcl_faq_speed_q3').text(chrome.i18n.getMessage('lcl_faq_speed_q3'))
$('.lcl_about_accounts').text(chrome.i18n.getMessage('lcl_about_accounts'))
$('.lcl_faq_accounts_q1').text(chrome.i18n.getMessage('lcl_faq_accounts_q1'))
$('.lcl_faq_accounts_q2').text(chrome.i18n.getMessage('lcl_faq_accounts_q2'))
$('.lcl_faq_accounts_q3').text(chrome.i18n.getMessage('lcl_faq_accounts_q3'))
$('.lcl_about_settings').text(chrome.i18n.getMessage('lcl_about_settings'))
$('.lcl_faq_settings_q1').text(chrome.i18n.getMessage('lcl_faq_settings_q1'))
$('.lcl_faq_settings_q2').text(chrome.i18n.getMessage('lcl_faq_settings_q2'))
$('.lcl_faq_settings_q3').text(chrome.i18n.getMessage('lcl_faq_settings_q3'))
$('.lcl_faq_settings_q4').text(chrome.i18n.getMessage('lcl_faq_settings_q4'))
$('.lcl_about_other_questions').text(chrome.i18n.getMessage('lcl_about_other_questions'))
$('.lcl_faq_other_q1').text(chrome.i18n.getMessage('lcl_faq_other_q1'))
$('.lcl_faq_other_q2').text(chrome.i18n.getMessage('lcl_faq_other_q2'))
$('.lcl_faq_other_q3').text(chrome.i18n.getMessage('lcl_faq_other_q3'))
$('.lcl_faq_pool_a1').text(chrome.i18n.getMessage('lcl_faq_pool_a1'))
$('.lcl_faq_pool_a2_1').text(chrome.i18n.getMessage('lcl_faq_pool_a2_1'))
$('.lcl_faq_pool_a2_2').text(chrome.i18n.getMessage('lcl_faq_pool_a2_2'))
$('.lcl_faq_pool_a3').text(chrome.i18n.getMessage('lcl_faq_pool_a3'))
$('.lcl_faq_speed_a1').text(chrome.i18n.getMessage('lcl_faq_speed_a1'))
$('.lcl_faq_speed_a2_1').text(chrome.i18n.getMessage('lcl_faq_speed_a2_1'))
$('.lcl_faq_speed_a2_2').text(chrome.i18n.getMessage('lcl_faq_speed_a2_2'))
$('.lcl_faq_speed_a2_3').text(chrome.i18n.getMessage('lcl_faq_speed_a2_3'))
$('.lcl_faq_speed_a3').text(chrome.i18n.getMessage('lcl_faq_speed_a3'))
$('.lcl_faq_accounts_a1').text(chrome.i18n.getMessage('lcl_faq_accounts_a1'))
$('.lcl_faq_accounts_a2').text(chrome.i18n.getMessage('lcl_faq_accounts_a2'))
$('.lcl_faq_accounts_a3').text(chrome.i18n.getMessage('lcl_faq_accounts_a3'))
$('.lcl_faq_settings_a1').text(chrome.i18n.getMessage('lcl_faq_settings_a1'))
$('.lcl_faq_settings_a2').text(chrome.i18n.getMessage('lcl_faq_settings_a2'))
$('.lcl_faq_settings_a3').text(chrome.i18n.getMessage('lcl_faq_settings_a3'))
$('.lcl_faq_settings_a4').text(chrome.i18n.getMessage('lcl_faq_settings_a4'))
$('.lcl_faq_other_a1').text(chrome.i18n.getMessage('lcl_faq_other_a1'))
$('.lcl_faq_other_a2').text(chrome.i18n.getMessage('lcl_faq_other_a2'))
$('.lcl_faq_other_a3').text(chrome.i18n.getMessage('lcl_faq_other_a3'))
$('.lcl_instructions').text(chrome.i18n.getMessage('lcl_instructions'))
$('.lcl_chart').text(chrome.i18n.getMessage('lcl_chart'))
$('.lcl_refresh_all').text(chrome.i18n.getMessage('lcl_refresh_all'))

// Follow
$('.lcl_in_pool').text(chrome.i18n.getMessage('lcl_in_pool'))
$('.lcl_following').text(chrome.i18n.getMessage('lcl_following'))
$('.lcl_followed').text(chrome.i18n.getMessage('lcl_followed'))
document.getElementById('lcl_insrct_follow_1').innerHTML = chrome.i18n.getMessage('lcl_insrct_follow_1');
document.getElementById('lcl_insrct_follow_2').innerHTML = chrome.i18n.getMessage('lcl_insrct_follow_2');
$('.lcl_insrct_follow_3').text(chrome.i18n.getMessage('lcl_insrct_follow_3'))
document.getElementById('lcl_insrct_call_to_action_follow_videos').innerHTML = chrome.i18n.getMessage('lcl_insrct_call_to_action_follow_videos');
$('.lcl_followed_time').text(chrome.i18n.getMessage('lcl_followed_time'))

$('.lcl_time_intervals').text(chrome.i18n.getMessage('lcl_time_intervals'))
$('.lcl_pool_collect_intervals').text(chrome.i18n.getMessage('lcl_pool_collect_intervals'))
$('.lcl_filters').text(chrome.i18n.getMessage('lcl_filters'))
$('.lcl_pool_size_limit').text(chrome.i18n.getMessage('lcl_pool_size_limit'))
$('.lcl_pool_size_limit_desc').text(chrome.i18n.getMessage('lcl_pool_size_limit_desc'))
$('.lcl_sources').text(chrome.i18n.getMessage('lcl_sources'))
$('.lcl_follow_limit_24h').text(chrome.i18n.getMessage('lcl_follow_limit_24h'))
$('.lcl_follow_limit_24h_desc').text(chrome.i18n.getMessage('lcl_follow_limit_24h_desc'))
$('.lcl_limit24h').text(chrome.i18n.getMessage('lcl_limit24h'))
$('.lcl_follow_time_interval').text(chrome.i18n.getMessage('lcl_follow_time_interval'))
$('.lcl_follow_time_interval_desc').text(chrome.i18n.getMessage('lcl_follow_time_interval_desc'))
$('.lcl_between').text(chrome.i18n.getMessage('lcl_between'))
$('.lcl_and').text(chrome.i18n.getMessage('lcl_and'))
document.getElementById('lpdt_text').innerHTML = chrome.i18n.getMessage('lcl_lpdt_follow');
$('.lcl_follow_error_waittime').text(chrome.i18n.getMessage('lcl_follow_error_waittime'))
$('.lcl_follow_error_waittime_desc').text(chrome.i18n.getMessage('lcl_follow_error_waittime_desc'))
$('.lcl_wait').text(chrome.i18n.getMessage('lcl_wait'))
$('.lcl_follows_filters_desc').text(chrome.i18n.getMessage('lcl_follows_filters_desc'))
$('.lcl_advanced').text(chrome.i18n.getMessage('lcl_advanced'))
$('.lcl_sleep_times_advanced_desc').text(chrome.i18n.getMessage('lcl_sleep_times_advanced_desc'))
$('.lcl_license_about_to_expire_msg').text(chrome.i18n.getMessage('lcl_license_about_to_expire_msg'))
$('.lcl_license_expired_msg').text(chrome.i18n.getMessage('lcl_license_expired_msg'))

// Unfollow
$('.lcl_scanned').text(chrome.i18n.getMessage('lcl_scanned'))
$('.lcl_unfollowed').text(chrome.i18n.getMessage('lcl_unfollowed'))
document.getElementById('lcl_insrct_unfollow_1').innerHTML = chrome.i18n.getMessage('lcl_insrct_unfollow_1');
$('.lcl_insrct_unfollow_2').text(chrome.i18n.getMessage('lcl_insrct_unfollow_2'))
document.getElementById('lcl_insrct_call_to_action_unfollow_videos').innerHTML = chrome.i18n.getMessage('lcl_insrct_call_to_action_unfollow_videos');
$('.lcl_restricted_unfollow').text(chrome.i18n.getMessage('lcl_restricted_unfollow'))
$('.lcl_restricted_unfollow_desc').text(chrome.i18n.getMessage('lcl_restricted_unfollow_desc'))
$('.lcl_restricted_unfollow_checkbox').text(chrome.i18n.getMessage('lcl_restricted_unfollow_checkbox'))
$('.lcl_grace_period').text(chrome.i18n.getMessage('lcl_grace_period'))
$(".lcl_grace_period_desc").text(chrome.i18n.getMessage("lcl_grace_period_desc"))
$('.lcl_unfollow_limit_24h').text(chrome.i18n.getMessage('lcl_unfollow_limit_24h'))
$('.lcl_unfollow_limit_24h_desc').text(chrome.i18n.getMessage('lcl_unfollow_limit_24h_desc'))
$('.lcl_unfollow_time_interval').text(chrome.i18n.getMessage('lcl_unfollow_time_interval'))
$('.lcl_unfollow_time_interval_desc').text(chrome.i18n.getMessage('lcl_unfollow_time_interval_desc'))
$('.lcl_error_waittime').text(chrome.i18n.getMessage('lcl_error_waittime'))
$('.lcl_unfollow_error_waittime').text(chrome.i18n.getMessage('lcl_unfollow_error_waittime'))
$('.lcl_total').text(chrome.i18n.getMessage('lcl_total'))
$('.lcl_whitelist_current_follows').text(chrome.i18n.getMessage('lcl_whitelist_current_follows'))
$('.lcl_whitelist_current_follows_desc').text(chrome.i18n.getMessage('lcl_whitelist_current_follows_desc'))
$('.lcl_removals').text(chrome.i18n.getMessage('lcl_removals'))
$('.lcl_clear_white_list').text(chrome.i18n.getMessage('lcl_clear_white_list'))

// Like
$('.lcl_hashtags').text(chrome.i18n.getMessage('lcl_hashtags'))
$('.lcl_liked').text(chrome.i18n.getMessage('lcl_liked'))
document.getElementById('lcl_insrct_like_1').innerHTML = chrome.i18n.getMessage('lcl_insrct_like_1');
document.getElementById('lcl_insrct_like_2').innerHTML = chrome.i18n.getMessage('lcl_insrct_like_2');
$('.lcl_insrct_like_3').text(chrome.i18n.getMessage('lcl_insrct_like_3'))
document.getElementById('lcl_insrct_call_to_action_like_videos').innerHTML = chrome.i18n.getMessage('lcl_insrct_call_to_action_like_videos');
$('.lcl_tags').text(chrome.i18n.getMessage('lcl_tags'))
$('.lcl_liked_time').text(chrome.i18n.getMessage('lcl_liked_time'))

// Trends
$('.lcl_error_log_desc').text(chrome.i18n.getMessage('lcl_error_log_desc'))

// Account
$('.lcl_account_desc').text(chrome.i18n.getMessage('lcl_account_desc'))
$('.lcl_profile').text(chrome.i18n.getMessage('lcl_profile'))
$('.lcl_license').text(chrome.i18n.getMessage('lcl_license'))
$('.lcl_license_remaining').text(chrome.i18n.getMessage('lcl_license_remaining'))
$('.lcl_renew').text(chrome.i18n.getMessage('lcl_renew'))
$('.lcl_email').text(chrome.i18n.getMessage('lcl_email'))
$('.lcl_email_desc').text(chrome.i18n.getMessage('lcl_email_desc'))
$('.lcl_save').text(chrome.i18n.getMessage('lcl_save'))
$('.lcl_settings_transfer').text(chrome.i18n.getMessage('lcl_settings_transfer'))
$('.lcl_export').text(chrome.i18n.getMessage('lcl_export'))
$('.lcl_import').text(chrome.i18n.getMessage('lcl_import'))
$('.lcl_export_instruction').text(chrome.i18n.getMessage('lcl_export_instruction'))
$('.lcl_export_caution').text(chrome.i18n.getMessage('lcl_export_caution'))
$('.lcl_copy').text(chrome.i18n.getMessage('lcl_copy'))
$('.lcl_import_instruction').text(chrome.i18n.getMessage('lcl_import_instruction'))
$('.lcl_share').text(chrome.i18n.getMessage('lcl_share'))
$('.lcl_share_desc').text(chrome.i18n.getMessage('lcl_share_desc'))
$('.lcl_share_btn').text(chrome.i18n.getMessage('lcl_share_btn'))
$('.lcl_share_url').text(chrome.i18n.getMessage('lcl_share_url'))
$('.lcl_get').text(chrome.i18n.getMessage('lcl_get'))